### ISSUE TITLE
Headless large hitches 

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2079]
### Describe the bug?

When hosting a weekly event, after having 6+ people join, the headless is starting to have huge performance issues.
Users stop moving, voices are crackling and audio streams basically stop.

The headless does not appear to be crashing, it simply becomes unusable until it has to be manually shut down.

When a user joins while the headless is in this state, they will see all the other present users at spawn, seemingly having IK issues (see screenshots provided).

### To Reproduce

1. Launch headless
2. Gather people 
3. Wait around 10 minutes
4. Headless will start having performance issues until all users are frozen

### Expected behavior

Headless should be able to handle this load.

### Screenshots

Users frozen:
![Resonite_9M2ysqXMIR](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/3b1f37bd-2902-405d-8130-74d6dbc48520)

Screenshot from a user that joined showing all other users stuck at spawn during the issue:
![](https://i.j4.lc/ShareX/2024/05/2024-05-23%2022.54.40.webp)

### Resonite Version Number

2024.5.22.1274

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

From last test, custom, baremetal (see additional context below).
[cheesebox - 2024.5.22.1274 - 2024-05-23 19_44_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15422047/cheesebox.-.2024.5.22.1274.-.2024-05-23.19_44_21.log)

### Additional Context

Tested with three setups:
- Linode 16G server - Docker
- Custom 32G server - Docker
- Custom 32G server - Baremetal

In all three cases:
- Headless is downloaded from scratch

In the case of Linode:
- A fresh server is created every time

Mono version for baremetal:
```
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.3~deb11u1 Sat Feb 18 21:26:37 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

Mono version for Docker: `mono:latest` on DockerHub
Docker image for the headless is Shadowpanther's.

Linux version:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Worlds:
- Club Crystalline - Private (basically a fancy box)
- Blast Arena - `resrec:///G-RetroGames/R-7d1cbf0d-0180-4392-8262-9bc9c20a9e06`
- AGRA JP Yellow Line - `resrec:///G-United-Space-Force-N/R-96728ad3-a07b-4ab6-8cf5-f4086045bd4d`

Custom server is served by 10/10Gbps, Linode has 40/6Gbps.

This issue has been happening for the past three weeks, in worlds having a culling system or not.

### Reporters

U-j4 | j4.lc (Discord)

**Comment by Frooxius** [comment]
This is a bit too vague. I've seen headless run bigger events without this necessarily occurring. 

- Does this happen at particular points/actions? E.g. users joining/leaving?
- Does this happen when hosting a particular world? Or are you able to reproduce this even on empty grid? 
- Do you have any performance metrics? CPU usage, RAM usage, server FPS?

**Comment by shiftyscales** [comment]
This is also a duplicate of #1477.

**Comment by jae1911** [comment]
> This is also a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1477.

@shiftyscales 
It is not, this is a different issue, the join lag is not in question.

> Does this happen at particular points/actions? E.g. users joining/leaving?

@Frooxius 
This happens when the session reaches around 6+ players after around 10-15 minutes. It seems to be accelerated by spawning an audio stream.

> Does this happen when hosting a particular world? Or are you able to reproduce this even on empty grid?

For now, this has been reproduced on at least three worlds (see additional details), I will need to conduct a test on an empty grid.

> Do you have any performance metrics? CPU usage, RAM usage, server FPS?

I did not record server FPS but here are some metrics I pulled from Grafana (all times in UTC):

Baremetal (third test):

CPU
![firefox_tRZYhgZQXH](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/08b63959-6e34-4c3f-b308-bcfab62c7188)

RAM
![firefox_LxF6t2LeJH](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/e18b1107-4a34-4570-b29a-249dae80632a)

Docker (second test):

CPU (large pink line):
![firefox_oZwpsBDX2I](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/36786f7b-68df-454a-95fb-357473828611)

RAM (large purple line):
![firefox_dHgLPQa1my](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/81ab5ed0-9d6a-4b18-94e5-cca32a9f4ee0)
9-a388efb9a91a)

---

To re-iterate the issue, after running a while, with enough users, the session starts having issues.
Issues include:
- Players being frozen in place indefinitely (this is not a temporary thing)
- Voices breaking down (while still being able to somewhat hear other players)
- Audio streams either stopping completely or cutting every few seconds
- When a user joins while the headless is in this state, all other users will appear at spawn (see screenshots in original report)

**Comment by Frooxius** [comment]
@jae1911 When this happens, can you spawn the users debug string and see if the Delta messages & sync ticks are incrementing? 

It sounds to me like the data model or streams somehow stop updating properly. Or something gets clogged up somewhere. We need to isolate what and where.

I don't think this is really performance/load thing though given that everything just freezes. If it was performance, then it should still work, just be very laggy and sluggish, but a complete freeze suggest something just straight up breaks.

**Comment by jae1911** [comment]
> When this happens, can you spawn the users debug string and see if the Delta messages & sync ticks are incrementing?

Sure, I will organise two tests then:
- Regular world
- Gridspace

Using a baremetal install.

**Comment by Readun** [comment]
To add a bit more Information: The Usage suddenly spikes intensively.
The Server is capped at 45 fps and at 21 People there were only 3 Threads at ~ 80%, all other threads were idlying at 3-5%
Headless had a fps of 36-43 fps during that.

Then the sudden change to a full lockup -> 24 threads at what is posted above....

The day before we had it aswell, with 12-14 people. all 24T @ 60% with Headless fps at 10-20 fps.... it suddenly freed itself again after 2h with the same usercount.

Edit: My guess is, that the server locked up as we had 22 people this time, yesterday with 12-16 people it "survived" at 10-20fps but was horrible. Voice and QM were still fine!

**Comment by BlueCyro** [comment]
I see mono 6.8 as one of the only concrete mono versions you're listing. Mono is currently up to 6.12.0.2xx and greater at this point. Can you 100% confirm that you're using at least up to that version on all configs by running the version command?

I'd highly recommend updating mono for all of these configurations if it's anything less, just to be sure.

**Comment by jae1911** [comment]
Small update, I was on a headless hosted by @decoybird and Avantis and the locking issue happened.
I managed to get some screenshots of the tick sync panel:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/52db2d0d-87f3-4c5e-a1ef-9780f3691060)

I will still conduct another test during this week with an empty gridspace to see if the issue persists there and also put this panel around in the sessions this week on Wed and Thu to get more information.

**Comment by Readun** [comment]
We might have clue on what is causing it now after yesterdays event and it might actually be something on someones Avatar.
We will investigate futher with them, because that extreme change in CPU load should not happen. (2 Threads on 50% -> All 24 Threads). 
Tonight is another event and we gradually gonna take their avatar appart, everytime it is gonna happen again to pinpoint it down.

**Comment by Readun** [comment]
Update: Okay... Nevermind, it is not Avatar Specific.

God this is such a wonky thing to pin down DX
We were watching the problem continue with them heaving already switched to a light avatar and it went back down when someone left.
He reequiped the heavy avatar -> Nothing happend
Until Canadian Git joined and all cores went back up.


My current state Observation: It so far can be triggered or "Fixed" when people join/Leave or change their Avatars in a session.

**Comment by shiftyscales** [comment]
Could you try isolating that particular case, @Readun?

E.g. have the user equip the heavy avatar, have a secondary user join and see if that causes it?

I'm not sure why you ruled out it being avatar specific if the same avatar was in use for each of the occasions it happened.

**Comment by Readun** [comment]
Because it also went down while they were still wearing it.
Or we had instances were they weren't even there and it reapeared today. 

Im not sure how to futher pinpoint it down :/

It is really heavy for the Headless and we had expirienced full lockups when the headless only is a more reasonable 6 Threads CPU.
We dont need so many threads, if that "Bug" doesnt appear. 

We havent tried to rule out, if its only the headless client or the normal client too btw.

Is there anything Froox can do to be able to log the issue?

> From the log, it seems like the session network threads have possibly exploded and stopped processing data. There's an exception when shutting down, which sounds like something else exploded earlier, but wasn't caught in the log. We might need to add some additional logging.

**Comment by Frooxius** [comment]
Like I mentioned above, I don't think this really has anything to do with the actual performance, but rather something that completely breaks part of the networking code - like throwing an exception inside of it.

Typically performance problems will still keep the system chugging forward - just slowly and jittery. They will not result in a complete halt that never recovers.

I need to add more instrumentation to gather more data. We had this happen during BoTC yesterday as well, even when people were joining in simple avatars.

**Comment by Readun** [comment]
New rough Info we were able to observe:
The assumption that it is a specific Avatar from a friend solidifies again. Specificly in combination with the Asset Cleanup!

- He spawns in his Avatar 
-> No Issue, until the Asset Cleanup accures! (Saw hidden Avatar Fluff flash pink for a frame)
- High CPU Utílization, even when he deletes his Avatar.
- CPU goes down immidiatly, when triggering another Asset Cleanup.

Im a bit confused on what it could be, as we were already deleting a lot of his stuff from the Avatar before.
Now with the Asset Cleanup triggering it, we'll need to take a look at his meshes and Materials.

It is -not- the same like in #2213 as it goes back to normal and no Restart is required.

**Comment by Readun** [comment]
Okay, we went through futher testing, but I have no Idea how we can futher pinpoint it...

- It is related to an Asset on his Body Slot.
- When the Body is deleted, it stays, until the next Asset cleanup
- If the specific avatar asset folder is persistent and the Avatar is deleted. It stays, until said avatar asset folder is deleted & the Cleanup did its work.
- Deleting the body Node and Undoing it fixes the issue, but breaks a couple of links from the visimes.
- Moving every asset of the body slot over onto the Avatar does not help, it still creates that CPU load behaivior, when the cleanup accures.
- Recreated every Material under the affected Body slot. To be sure its not a problem from the past. (We did not reupload the textures tho..)


Im running out of Ideas what we can test futher :/

**Comment by Frooxius** [comment]
I'm adding some extra diagnostics in the next build. I'm starting to build a suspicion this might be a deadlock in one of the threads. 

Which is a bit unfortunate, but it could be an excuse needed to rewrite this system (which would also solve a number of other issues).

**Comment by Frooxius** [comment]
Okay the diagnostic command is now in 2024.6.24.1317!

If the session freezes your headless, type this command and save the output. Then type it again a few seconds later and save the output again. And post it here.

**Comment by shiftyscales** [comment]
Since it didn't seem to be mentioned in the issue itself, the command is `debugWorldState` @jae1911 @Readun.

> Added debugWorldState command to headless, which prints out debugging info for state of all worlds (this is to help diagnose issue reported by @ Jae “awa” J4, @ Readun, @ Hikari Akimori, @ Ink_25, issue #2079)
> -- If the session freezes your headless, type this command and save the output. Then type it again a few seconds later and save the output again.

**Comment by Readun** [comment]
Mmnnhhh... @Frooxius this is slightly tricky.
Does this work when the headless also just get that high load?
The Headless freezes with this specific bug only when the Headless CPU isnt powerfull enough.

Does it still output the desired diagnostic or is this only specific for a freeze?

Gonna try it in the evening.

**Comment by Frooxius** [comment]
I don't know. I just need you to run the command when this issue happens and see what it outputs (or if anything else happens).

**Comment by Readun** [comment]
Will do!

**Comment by Banane9** [comment]
> I'm starting to build a suspicion this might be a deadlock in one of the threads.

That was my first suspicion too after reading

> The Headless freezes with this specific bug only when the Headless CPU isnt powerfull enough.

Would make perfect sense to explain why it only gets stuck when something else isn't done fast enough.

**Comment by Readun** [comment]
Okay, just tested it:

With the issue
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76232047/217eabc9-d6eb-4d7c-841a-889a78c5f5f7)

After the Issue:
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76232047/c115e46f-d1c7-4a23-a957-dd8150364351)

**Comment by Readun** [comment]
The first one is with that bug accuring, the second one after is after Ink removed the problematic avatar & the Asset Cleanup took place.

Okay, another test with only 4 Threads..... @jae1911 we need to test this with a Linux headless. Apparently a Windows Headless does not "Freeze" fully.

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76232047/77cf4573-8bb2-41b5-9376-2f71b38e6c17)

[READUNSERVER - 2024.6.24.1317 - 2024-06-25 19_11_57.log](https://github.com/user-attachments/files/15975226/READUNSERVER.-.2024.6.24.1317.-.2024-06-25.19_11_57.log)


I will try another quick test with just one thread to be fully sure...

**Comment by Frooxius** [comment]
Wait, I'm a bit more confused - so you're able to unfreeze the session by deleting something? And then it continues as normal?

In order to diagnose this, I need two outputs of that command **while** everything is frozen - I need to see what's happening during everything being frozen at two distinct points in time. That's why I asked to wait a few seconds and type it again. 

Otherwise this won't be very useful.

**Comment by Readun** [comment]
> * He spawns in his Avatar
>   -> No Issue, until the Asset Cleanup accures! (Saw hidden Avatar Fluff flash pink for a frame)
> 
> * High CPU Utílization, even when he deletes his Avatar.
> 
> * CPU goes down immidiatly, when triggering another Asset Cleanup.

Yes, described here. All that from me is with a Windows Headless. @jae1911 is booting up his Linux headless right now to do futher testing and Im restricting mine to 1 Thread.




> I need two outputs of that command **while** everything is frozen

In my last screenshoot with 4 threads, I wrote "Starting now" into the command line, when we triggered the bug.

**Comment by Readun** [comment]
This is with 1 Thread. But I noticed this is not a suitable state!
The Voice seems to die with only one thread avaible, Ink_25 wasnt able to hear me.
The Headless itself already spiked to 100% on that one core, when just typing debugworldstate

This is with the bug triggered, it does not freeze on Windows.
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76232047/282354f9-f23c-4971-93ed-991ea39cf168)



Next up is Testing Linux headless with @jae1911 !

**Comment by Frooxius** [comment]
I'm not fully clear on the sequence of events there. You mention high CPU utilization, but I'm not sure if that means that everything in the session is frozen? Similarly when there's low CPU utilization, if that means that everything is unfrozen - you could have low CPU utilization, while session still remains frozen.

Can you explicitly specify  when session freezes and when it unfreezes please? It's a bit ambiguous on what correlates to what.

------------------------------

From the screenshot however, it doesn't actually seem like this is a deadlock at all - the sync threads keep processing. 

If the session is able to unfreeze as well, that would also indicate that something completely different is at play. We'd probably need to isolate the item that needs to be deleted to unfreeze everything (e.g. by deleting it piece by piece).

------------------------------

Actually this brings another question - when a new user joins after the server is already frozen, is everything frozen for them too?

**Comment by jae1911** [comment]
> Actually this brings another question - when a new user joins after the server is already frozen, is everything frozen for them too?

In my original testing, this is what happens, everybody is frozen at spawn (see screenshot in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2079#issue-2313752060)

**Comment by Readun** [comment]
I have the feeling this is a mixture of having this specific bug + having a lot of players in the session to overwhelm a specific process.
We are now using J4s Linux headless with that we had the freeze issue. -> It has similiar symptoms of high cpu utulization but it doesnt freeze.
We gonna try to invite a couple people quick!
AAaaaand it happend, J4 will report!




> Can you explicitly specify when session freezes and when it unfreezes please? It's a bit ambiguous on what correlates to what.

As written above, it is Ink_25 Body-slot and Assets.
We tried to figure out what asset, but we were at it for hours x..x

vvvv


> Okay, we went through futher testing, but I have no Idea how we can futher pinpoint it...
> 
>     * It is related to an Asset on his Body Slot.
> 
>     * When the Body is deleted, it stays, until the next Asset cleanup
> 
>     * If the specific avatar asset folder is persistent and the Avatar is deleted. It stays, until said avatar asset folder is deleted & the Cleanup did its work.
> 
>     * Deleting the body Node and Undoing it fixes the issue, but breaks a couple of links from the visimes.
> 
>     * Moving every asset of the body slot over onto the Avatar does not help, it still creates that CPU load behaivior, when the cleanup accures.
> 
>     * Recreated every Material under the affected Body slot. To be sure its not a problem from the past. (We did not reupload the textures tho..)
> 
> 
> Im running out of Ideas what we can test futher :/

**Comment by jae1911** [comment]
Alright, as for the Linux test.

Here is without the bug happening (before triggering anything):
```
DN0 World 0>debugWorldState
World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: DN0 World 0, Handle: 2
        WorldStage: RefreshBegin
        SyncTick: 11256
        WorldSessionState: WaitingForSyncThreadEvent
        WorldSessionStopProcessing: False
        WorldMessagesToProcess: 0
        WorldTotalProcessedMessages: 24908
        WorldMessagesToTransmit: 0
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
DN0 World 0>
```

The bug starts (all cores start being 80-98% all the time):
```
World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test, Handle: 2
        WorldStage: PhysicsMoved
        SyncTick: 78656
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 2
        WorldTotalProcessedMessages: 361268
        WorldMessagesToTransmit: 0
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
```

Everybody is frozen:
```
World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test - Bug testing (WE NEED PLAYERS), Handle: 2
        WorldStage: ProtoFluxContinuousChanges
        SyncTick: 86297
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 2
        WorldTotalProcessedMessages: 484363
        WorldMessagesToTransmit: 7246
        ProcessingSyncMessage:
        CurrentlyDecodingStream:

World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test - Bug testing (WE NEED PLAYERS), Handle: 2
        WorldStage: ProtoFluxContinuousChanges
        SyncTick: 86452
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 18
        WorldTotalProcessedMessages: 492286
        WorldMessagesToTransmit: 10852
        ProcessingSyncMessage:
        CurrentlyDecodingStream:

World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test - Bug testing (WE NEED PLAYERS), Handle: 2
        WorldStage: ProtoFluxContinuousChanges
        SyncTick: 86554
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 11
        WorldTotalProcessedMessages: 495155
        WorldMessagesToTransmit: 12303
        ProcessingSyncMessage:
        CurrentlyDecodingStream:

World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test - Bug testing (WE NEED PLAYERS), Handle: 2
        WorldStage: ProtoFluxUpdates
        SyncTick: 86651
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 15
        WorldTotalProcessedMessages: 498137
        WorldMessagesToTransmit: 12590
        ProcessingSyncMessage:
        CurrentlyDecodingStream:

World: Userspace, Handle: 1
        WorldStage: RefreshBegin
        SyncTick: 1
        WorldSessionState:
        WorldSessionStopProcessing:
        WorldMessagesToProcess:
        WorldTotalProcessedMessages:
        WorldMessagesToTransmit:
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
World: 2079 Linux Test - Bug testing (WE NEED PLAYERS), Handle: 2
        WorldStage: ProtoFluxUpdates
        SyncTick: 86758
        WorldSessionState: ProcessingStopped
        WorldSessionStopProcessing: True
        WorldMessagesToProcess: 15
        WorldTotalProcessedMessages: 501819
        WorldMessagesToTransmit: 12971
        ProcessingSyncMessage:
        CurrentlyDecodingStream:
```

Log files: 
[cheesebox - 2024.6.24.1317 - 2024-06-25 17_28_09.log](https://github.com/user-attachments/files/15975750/cheesebox.-.2024.6.24.1317.-.2024-06-25.17_28_09.log)
