### ISSUE TITLE
Headless does not run with included freetype libraries

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#4222]
### Describe the bug?

When trying to run a headless on a system without freetype libraries installed, Resonite will fail to start.

If you install freetype libraries (e.g. the `libfreetype6` package on Debian), the Resonite headless will start as normal.

### To Reproduce

Try and run the headless on a system without freetype libraries installed.

The following Docker compose file will try and run a headless in an environment where these are not installed:
```
services:
  headless:
    container_name: resonite-headless
    image: ghcr.io/voxelbonecloud/resonite-headless-docker:nofreetype 
    environment:
      # Set SKIP_STEAM_UPDATE to true to skip updating Resonite through Steam
      SKIP_STEAM_UPDATE: false
      STEAM_USER: "SomeSteamUsername"
      STEAM_PASS: "SomeSteamPassword"
      BETA_CODE: "ResoniteHeadlessKey"
    tty: true
    stdin_open: true
    user: "1000:1000"
    volumes:
    # Make sure you create a directory called "install" next to this compose file!
    # Resonite will be installed into this directory.
      - "./install:/home/container/install"
```

Source for the Docker image can be found at https://github.com/voxelbonecloud/resonite-headless-docker/tree/nofreetype

You will need to create a directory called `install` alongside this compose file - the Resonite headless files will be installed there.

Steam updating can be disabled by setting `SKIP_STEAM_UPDATE` to `true`

### Expected behavior

Headless to run with included freetype library

### Resonite Version Number

Beta 2025.4.10.1305

### What Platforms does this occur on?

Linux

### Log Files

[a4a49e640cdd - 2025.4.10.1305 - 2025-05-01 05_33_56.log](https://github.com/user-attachments/files/19996876/a4a49e640cdd.-.2025.4.10.1305.-.2025-05-01.05_33_56.log)

### Reporters

bredo
